version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    labels:
      - 'dependencies'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '02:46'
    commit-message:
      include: 'scope'
      prefix: 'chore(deps): '
    allow:
      - dependency-type: 'all'
    cooldown:
      default-days: 2
